import type { Metadata } from "next";
import { roboto } from "./fonts"

import "./globals.css";

import NavigationBar from "./ui/nav"

import { FoodProvider } from "./hooks/foods"

export const metadata: Metadata = {
  title: "FitCal",
  description: "Generated by create next app",
};

export default function RootLayout(properties: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ roboto.className }>
        <FoodProvider>
          <div className="page-content">
            { properties.children }
          </div>
          <NavigationBar />
        </FoodProvider>
      </body>
    </html>
  );
}
